### PR TITLE
Commits for issues #7 and #8

### PR DESCRIPTION
**Pull request by emmdim**
Check them before accept.

### CODE REVIEW

**Comment by emmdim** [comment]
Last commit fails the test. The issue is that following the CNML structure CNMLInterface is not necesarily the child of a CNMLRadio but can also be a child of a CNMLDevice as well. While the parsing is done correctly the attribute parentRadio for CNMLInterface object is misleading.

**Comment by emmdim** [comment]
@PabloCastellano  any comment?

**Comment by nemesifier** [comment]
@emmdim I think the tests need to be updated, this change should go in a new release (likely 0.10) indicating there's a backward incompatible change in the changelog.

**Comment by emmdim** [comment]
@nemesisdesign @PabloCastellano 
Ok. In general I have a variety of commits that can be added. Some make the library more compatible with guifi CNML some are generic.
Here you can see all of them:
https://github.com/emmdim/guifiAnalyzer/commits/master/lib/libcnml

The most important is (already based on my version of libcnml though):
https://github.com/emmdim/guifiAnalyzer/commit/51a5d6be98e9799521cc51dde80515861d981d0f#diff-ccf834792b38a4dcacd8228ba741928d

**Comment by itorres** [comment]
@PabloCastellano shouldn't this PR be closed since you fixed the issues in other commits?
- #8 fixed in https://github.com/PabloCastellano/libcnml/commit/7f7ee6493c66ef3c185d981d68037f5111ce7d4a on Feb 2, 2016
- #7 fixed in https://github.com/PabloCastellano/libcnml/commit/9d2a249a1136cbb856c947ea14de02423844a267  on Feb 6, 2016

**Comment by PabloCastellano** [comment]
You're right. Closing.

**Pull request closed without merging**
